name: Check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
        cache-target: release
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lints:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
        cache-target: release
        components: clippy,rustfmt
    - uses: actions/setup-python@v6
    - uses: pre-commit/action@v3.0.1
