name: stable

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
        cache-target: release
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
